### PR TITLE
MDXView Update

### PR DESCRIPTION
**Pull request by DT85**
- Ghoul2 models now render, just UVs aren't working. This is a band aid solution, as we need to properly update the original modview code to work with GLSL for things like UVs etc. May need to change view mode to wireframe on some models to see them (eg. kyle).
- Added "include" directory, stored all required external files there.
- Re-directed output files to a better location.
- Added copying of GLSL shaders to the output directory during compile.
- Release build now compiles, but program freezes when loading a ghoul2 model.
- Put all things related to the default cube mesh under the ifdef CUBE.

### CODE REVIEW

**Review by Archangel35757 — APPROVED** [review]
Thanks.

**Comment by SamHatami** [comment]
Hi Archangel! I found that you had update a 3dsmax md3 exporter to version 2020. Is there a chance to get the source code from that so I perhaps can compile it into 2024? Unless you already have done something similar already?

**Comment by Archangel35757** [comment]
Hello Sam,

I think I’ve actually compiled it for versions after 2020, at least for 2021, 2022,and 2023.  Let me check if I compiled it also for 2024.  If not, if you will send me the Max2024 SDK installer I will recompile it for Max2024. I will let you know shortly.

 

Thanks,

Michael

**Comment by SamHatami** [comment]
Hey! Thanks for replying!

I would assume that if you've compiled it for 2023 it would work for 2024. I could always test it.

You can get 3ds max 2024 sdk here https://aps.autodesk.com/developer/overview/3ds-max#3dsmax-sdk

Thanks!
________________________________
Från: Archangel35757 ***@***.***>
Skickat: den 1 september 2023 15:07
Till: Archangel35757/MDXView ***@***.***>
Kopia: SamHatami ***@***.***>; Comment ***@***.***>
Ämne: Re: [Archangel35757/MDXView] MDXView Update (PR #1)


Hello Sam,

I think I’ve actually compiled it for versions after 2020, at least for 2021, 2022,and 2023. Let me check if I compiled it also for 2024. If not, if you will send me the Max2024 SDK installer I will recompile it for Max2024. I will let you know shortly.



Thanks,

Michael

**Comment by Archangel35757** [comment]
Hello Sam,

 

Looks like I have compiled it for version up thru Max2023.  I already have the Max2024 SDK so I will compile it for you later today.  The reason I never posted the newer versions is I was waiting for some user feedback… but no one ever tells me if there are any problems—by their lack of communication I guess there are no problems for 2021-2023.

 

Cheers,

Michael

**Comment by SamHatami** [comment]
Awesome thanks!

**Comment by Archangel35757** [comment]
Sam,

 

Please find attached to this email the MD3 Exporter plugin v2.4 for 3ds Max 2024.  

 

It seems the Max2024 SDK was upgraded to VS 2019… however, I recompiled my project using VS 2017.  It should work… there were a few modifications to the SDK that required me to add unique changes for R2024.

 

Please test it out and let me know if it works.  There were some changes and fixes in the v2.4 plugin.  I need to recompile all versions and update the plugin-pack on JKHub.org and Maxplugins.de

 

 

Notes on v2.4:

 

1.  This version will make sure the shader path does not exceed the game limit of MAX_QPATH (64 characters)... if shader path violates this you will get a new warning.  The shader name is also written out into the statistics output for each mesh surface.

 

2.  There was some discussion among some beta tester artists about shaders and file extensions used in the Material Editor diffuse name.  So I added code to replace any extension with “.tga” and you’ll see that written out in statistics now.

 

https://cdn.discordapp.com/attachments/238014547233996801/857985582730706944/new_export_stats.png

 

For a previous release of 3dsMax v2.4 plugin, I quickly exported out a simple textured box using a png checker-pattern (unchecking 'use material name' to evaluate the *.tga extension swap-- looks like it worked!)

 

I’m going to have to comb back thru the Discord discussion and create a complete list of changes for v2.4… another fix involved removing duplicate vertex normals if I recall correctly.

 

Let me know how it works for you please.

 

Cheers,

Michael

**Comment by Archangel35757** [comment]
Did it work for you?

Sent from Yahoo Mail on Android 
 
  On Fri, Sep 1, 2023 at 8:22 AM, ***@***.***> wrote:   

Hey! Thanks for replying!

I would assume that if you've compiled it for 2023 it would work for 2024. I could always test it.

You can get 3ds max 2024 sdk here https://aps.autodesk.com/developer/overview/3ds-max#3dsmax-sdk

Thanks!
________________________________
Från: Archangel35757 ***@***.***>
Skickat: den 1 september 2023 15:07
Till: Archangel35757/MDXView ***@***.***>
Kopia: SamHatami ***@***.***>; Comment ***@***.***>
Ämne: Re: [Archangel35757/MDXView] MDXView Update (PR #1)


Hello Sam,

I think I’ve actually compiled it for versions after 2020, at least for 2021, 2022,and 2023. Let me check if I compiled it also for 2024. If not, if you will send me the Max2024 SDK installer I will recompile it for Max2024. I will let you know shortly.



Thanks,

Michael

**Comment by SamHatami** [comment]
Hi!

I havent had the chance to try it out, but hopefully will today, a very big thank you that you pulled together this one so quickly.

i'll return asap,

again, thank you very much!

Sam

________________________________

**Comment by SamHatami** [comment]
hi again Micheal!

It seem that the attachment wasn't attached to this mail.

Try sending it directly to ***@***.***

Thanks,

Sam
________________________________
Från: Archangel35757 ***@***.***>
Skickat: den 1 september 2023 18:06
Till: Archangel35757/MDXView ***@***.***>
Kopia: SamHatami ***@***.***>; Comment ***@***.***>
Ämne: Re: [Archangel35757/MDXView] MDXView Update (PR #1)


Sam,



Please find attached to this email the MD3 Exporter plugin v2.4 for 3ds Max 2024.



It seems the Max2024 SDK was upgraded to VS 2019… however, I recompiled my project using VS 2017. It should work… there were a few modifications to the SDK that required me to add unique changes for R2024.



Please test it out and let me know if it works. There were some changes and fixes in the v2.4 plugin. I need to recompile all versions and update the plugin-pack on JKHub.org and Maxplugins.de





Notes on v2.4:



1. This version will make sure the shader path does not exceed the game limit of MAX_QPATH (64 characters)... if shader path violates this you will get a new warning. The shader name is also written out into the statistics output for each mesh surface.



2. There was some discussion among some beta tester artists about shaders and file extensions used in the Material Editor diffuse name. So I added code to replace any extension with “.tga” and you’ll see that written out in statistics now.



https://cdn.discordapp.com/attachments/238014547233996801/857985582730706944/new_export_stats.png



For a previous release of 3dsMax v2.4 plugin, I quickly exported out a simple textured box using a png checker-pattern (unchecking 'use material name' to evaluate the *.tga extension swap-- looks like it worked!)



I’m going to have to comb back thru the Discord discussion and create a complete list of changes for v2.4… another fix involved removing duplicate vertex normals if I recall correctly.



Let me know how it works for you please.



Cheers,

Michael

**Comment by Archangel35757** [comment]
Your email was blocked.  Seems GitHub stripped out the attachment.  Send me an email to my GitHub username at yah00_dot_com
Cheers.

Sent from Yahoo Mail on Android 
 
  On Sat, Sep 2, 2023 at 1:45 AM, ***@***.***> wrote:   

hi again Micheal!

It seem that the attachment wasn't attached to this mail.

Try sending it directly to ***@***.***

Thanks,

Sam
________________________________
Från: Archangel35757 ***@***.***>
Skickat: den 1 september 2023 18:06
Till: Archangel35757/MDXView ***@***.***>
Kopia: SamHatami ***@***.***>; Comment ***@***.***>
Ämne: Re: [Archangel35757/MDXView] MDXView Update (PR #1)


Sam,



Please find attached to this email the MD3 Exporter plugin v2.4 for 3ds Max 2024.



It seems the Max2024 SDK was upgraded to VS 2019… however, I recompiled my project using VS 2017. It should work… there were a few modifications to the SDK that required me to add unique changes for R2024.



Please test it out and let me know if it works. There were some changes and fixes in the v2.4 plugin. I need to recompile all versions and update the plugin-pack on JKHub.org and Maxplugins.de





Notes on v2.4:



1. This version will make sure the shader path does not exceed the game limit of MAX_QPATH (64 characters)... if shader path violates this you will get a new warning. The shader name is also written out into the statistics output for each mesh surface.



2. There was some discussion among some beta tester artists about shaders and file extensions used in the Material Editor diffuse name. So I added code to replace any extension with “.tga” and you’ll see that written out in statistics now.



https://cdn.discordapp.com/attachments/238014547233996801/857985582730706944/new_export_stats.png



For a previous release of 3dsMax v2.4 plugin, I quickly exported out a simple textured box using a png checker-pattern (unchecking 'use material name' to evaluate the *.tga extension swap-- looks like it worked!)



I’m going to have to comb back thru the Discord discussion and create a complete list of changes for v2.4… another fix involved removing duplicate vertex normals if I recall correctly.



Let me know how it works for you please.



Cheers,

Michael

**Comment by SamHatami** [comment]
H I sent mail but perhaps it went to your trash bin. from mhatami at hotmail.com
________________________________
Från: Archangel35757 ***@***.***>
Skickat: den 3 september 2023 04:09
Till: Archangel35757/MDXView ***@***.***>
Kopia: SamHatami ***@***.***>; Comment ***@***.***>
Ämne: Re: [Archangel35757/MDXView] MDXView Update (PR #1)


Your email was blocked.  Seems GitHub stripped out the attachment.  Send me an email to my GitHub username at yah00_dot_com
Cheers.

Sent from Yahoo Mail on Android

On Sat, Sep 2, 2023 at 1:45 AM, ***@***.***> wrote:

hi again Micheal!

It seem that the attachment wasn't attached to this mail.

Try sending it directly to ***@***.***

Thanks,

Sam
________________________________
Från: Archangel35757 ***@***.***>
Skickat: den 1 september 2023 18:06
Till: Archangel35757/MDXView ***@***.***>
Kopia: SamHatami ***@***.***>; Comment ***@***.***>
Ämne: Re: [Archangel35757/MDXView] MDXView Update (PR #1)


Sam,



Please find attached to this email the MD3 Exporter plugin v2.4 for 3ds Max 2024.



It seems the Max2024 SDK was upgraded to VS 2019… however, I recompiled my project using VS 2017. It should work… there were a few modifications to the SDK that required me to add unique changes for R2024.



Please test it out and let me know if it works. There were some changes and fixes in the v2.4 plugin. I need to recompile all versions and update the plugin-pack on JKHub.org and Maxplugins.de





Notes on v2.4:



1. This version will make sure the shader path does not exceed the game limit of MAX_QPATH (64 characters)... if shader path violates this you will get a new warning. The shader name is also written out into the statistics output for each mesh surface.



2. There was some discussion among some beta tester artists about shaders and file extensions used in the Material Editor diffuse name. So I added code to replace any extension with “.tga” and you’ll see that written out in statistics now.



https://cdn.discordapp.com/attachments/238014547233996801/857985582730706944/new_export_stats.png



For a previous release of 3dsMax v2.4 plugin, I quickly exported out a simple textured box using a png checker-pattern (unchecking 'use material name' to evaluate the *.tga extension swap-- looks like it worked!)



I’m going to have to comb back thru the Discord discussion and create a complete list of changes for v2.4… another fix involved removing duplicate vertex normals if I recall correctly.



Let me know how it works for you please.



Cheers,

Michael

**Pull request merged**
